---
- hosts: wordpress
  become_user: root
  vars:
   mysql_root_password: redhat
   wp_user_password: password
   server_name: wordpress.example.com

  tasks:
     
      - name: install epel
        yum: name=epel-release state=present

      - name: Install nginx
        yum: name=nginx state=present

      - name: Install php-moules
        yum: 
          name: "{{ item }}"
        with_items:
          - php
          - php-common
          - php-mysql
          - php-gd
          - php-xml
          - php-mbstring
          - php-mcrypt
          - php-fpm
  
      - name: php-fpm config
        command: /usr/bin/sed -i -e "s/;cgi.fix_pathinfo=1/cgi.fix_pathinfo=0/g" /etc/php.ini
      
      - name: create log directory
        file: path=/usr/share/nginx/wordpress/logs state=directory owner=nginx group=nginx mode=755 

     # - name: create sites-enabled,sites-available directory
     #   file: path="{{ item }}" state=directory
     #  with_items:
     #      - /etc/nginx/sites-available
     #      - /etc/nginx/sites-enabled

    
      - name: copy wordpress-nginx config file
        template: src=/root/ans-wordpress/wordpress.j2 dest=/etc/nginx/conf.d/default.conf
    
 
     # - name: make a link of your config file in site-enabled
     #   shell: /usr/bin/ln -s /etc/nginx/sites-available/wordpress /etc/nginx/sites-enabled/wordpress.conf

     # - name: Add the follwing line of code in nginx-config file
     #   shell: /usr/bin/echo "include /etc/nginx/sites-enabled/*;" >> /etc/nginx/nginx.conf
      
      - name: Extract the tar
        unarchive:
              src: /root/ans-wordpress/latest.tar.gz
              dest: /usr/share/nginx/
              owner: nginx
              group: nginx

      - name: Copy the config file
        template: src=/root/ans-wordpress/wp-config.php.j2 dest=/usr/share/nginx/wordpress/wp-config.php owner=nginx group=nginx

      - name: start the nginx service
        service: name=nginx state=started
      
      - name: Install Mysql on Centos or rhel
        yum:
          name: "{{ item }}"
        with_items:
          - mariadb
          - mariadb-server
          - MySQL-python

   #   - name: Install Mysql on ubuntu
   #     apt:
   #       name: "{{ item }}"
   #     with_items:
   #        - mariadb-server
   #        - mariadb-client
   #        - MySQL-python
   #     when: ansible_distribution == 'Ubuntu'
         

      - name: copy .my.cnf file with root password credentials
        copy: src=/root/ans-wordpress/.my.cnf dest=/root/.my.cnf mode=600 owner=root

      - name: Start mysql
        service: name=mariadb state=started

      - name: start php-fpm service
        service: name=php-fpm state=started enabled=yes

      - name: update mysql password
        mysql_user:
              name: root
              host: "{{ item }}"
              password: "{{ mysql_root_password }}"
              login_user: root
              check_implicit_admin: yes
              priv: "*.*:ALL,GRANT"
        with_items:
              - 127.0.0.1
              - ::1
              - localhost
       
      - name: create mysql db
        mysql_db: name=wordpress state=present

      - name: create mysql user
        mysql_user:
              name: wp_user
              host: localhost
              state: present
              password: "{{ wp_user_password }}"
              priv: "wordpress.*:ALL,GRANT"               

    
